version : '3.7'

services: 
    
    HelloworldRestApiDB:
       image: my-rest-api-docker-80
       ports:
          - "8000:8000"
       restart: always     
       depends_on:
          - docker
       networks: 
          - my-rest-network
          
    HelloworldRestApiClient:
       image: hello-world-client
       ports:
          - "8100:8100"
       restart: always
       depends_on:   
          - HelloworldRestApiDB
       networks: 
          - my-rest-network
    
    docker:
       image: mysql:8
       networks:
          - my-rest-network
       environment:
          - MYSQL_ROOT_PASSWORD=password
          - MYSQL_DATABASE=docker

          
networks:
   my-rest-network: